#:schema node_modules/wrangler/config-schema.json
name = "sublink"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "ced9ce7c0c2145dcbd4d0074e8b6cd44" }
]
